#!/bin/bash

cd $(dirname $0)/../src
PATH=$(pwd):$PATH

dir=$(mktemp -d)
trap "rm -rf $dir" EXIT
cd $dir

git init

# Initial commit
echo "Initial junk" > aaa-junk.txt
git add aaa-junk.txt
git commit -m "Initial"
git tag initial

# Second commit, with Review-Options
echo "Important stuff" > zzz-important.txt
echo "Support junk for the important stuff" > aaa-junk.txt
git add *.txt
git commit \
    -m "Important work" \
    -m 'Review-Options: --order=*.h,*important.txt -M'

# Third commit, with Review-Options
echo "More important stuff" > zzz-important.txt
echo "Support junk for more important stuff" > aaa-junk.txt
git add *.txt
git commit \
    -m "More important work" \
    -m 'Review-Options: --order=*.h,*important.txt -M'

# This time with Review-Section
echo "Even more important stuff" >> zzz-important.txt
echo "Support junk for more important stuff" > aaa-junk.txt
git add *.txt
git commit \
    -m "More important work" \
    -m 'Review-Section: *.h,*important.txt'

# Compare git-review and git-show
args="--oneline --stat initial.."

echo
echo "----------"
echo "'git review $args' output:"
echo "----------"
git review $args

echo
echo "----------"
echo "'git show $args' output:"
echo "----------"
git show $args
