#!/bin/bash

function usage() {
    echo "Usage: $0 [<options>] [<object>...]"
}

if [ "$1" == "--help" ]; then
    usage
    exit 0
fi


order=
diff_options=

function parse_options() {
    while [ $# -ne 0 ]; do
        if [[ "$1" == --order=* ]]; then
            order="$order$(echo "$1" | sed 's/--order=//' | tr ',' '\n')
"
        elif [[ "$1" == "-M" || "$1" == "-w" ]]; then
            diff_options="$diff_options $1"
        else
            echo "Ignoring unknown Review-Options flag: $1" >&2
        fi
        shift
    done
}

function parse_sections() {
    # Treat each as an additional glob pattern; add them to 'order'
    while [ $# -ne 0 ]; do
        order="$order$(echo "$1" | tr ',' '\n')
"
        shift
    done
}

revs=$(git rev-parse --no-flags --default HEAD "$@")
review_options=$(git show --no-patch --format=%B $revs \
    | egrep '^Review-Options:' \
    | sed 's/[^:]*://')
parse_options $review_options

review_sections=$(git show --no-patch --format=%B $revs \
    | egrep '^Review-Section:' \
    | sed 's/[^:]*://')
parse_sections $review_sections


exec git show $diff_options -O <(echo "$order") "$@"
