#!/bin/bash

set -eou pipefail

function usage() {
    echo "Usage: $0 [<options>] [<object>...]"
}

if [ "$#" -gt 0 ] && [ "$1" == "--help" ]; then
    usage
    exit 0
fi


function parse_options() {
    while [ $# -ne 0 ]; do
        if [[ "$1" == --order=* ]]; then
            order="$order$(echo "$1" | sed 's/--order=//' | tr ',' '\n')
"
        elif [[ "$1" == "-M" || "$1" == "-w" ]]; then
            diff_options="$diff_options $1"
        else
            echo "Ignoring unknown Review-Options flag: $1" >&2
        fi
        shift
    done
}

function parse_sections() {
    # Treat each as an additional glob pattern; add them to 'order'
    while [ $# -ne 0 ]; do
        order="$order$(echo "$1" | tr ',' '\n')
"
        shift
    done
}


pager="$(git config core.pager || true)"
pager="${pager:-less -RFX}"

revs=$(git rev-parse --revs-only --default HEAD "$@")
opts=$(git rev-parse --no-revs "$@")
for rev in $(git log --format='%H' $revs); do
    order=
    diff_options=
    
    review_options=$(git show --no-patch --format=%B $rev \
                         | egrep '^Review-Options:' \
                         | sed 's/[^:]*://' || true)
    parse_options $review_options

    review_sections=$(git show --no-patch --format=%B $rev \
                          | egrep '^Review-Section:' \
                          | sed 's/[^:]*://'|| true)
    parse_sections $review_sections

    git -P -c color.ui=always show $opts $diff_options -O <(echo "$order") $rev
done | $pager | less -RFX # When using a pipelined core.pager, we somehow need an extra 'less' to page
